apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: security-apps-matrix
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/mabusaa/argocd-example-apps.git
          revision: master
          directories:
          - path: helmcharts/security-policy-charts/*
      - clusters:
          selector:
            matchLabels:
              non-prod: "true"
  template:
    metadata:
      name: '{{ nameNormalized }}-{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/mabusaa/argocd-example-apps.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{ nameNormalized }}-{{path.basename}}'
      syncPolicy:
         syncOptions:
          - CreateNamespace=true