apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp-review
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: sakshirathoree
        # The Github repository
        repo: argocd-course-webapp
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - preview
      requeueAfterSeconds: 90
  template:
    metadata:
      name: 'webapp-{{branch}}-{{number}}'
      namespace: argocd
    spec:
      source:
        repoURL: 'https://github.com/sakshirathoree/argocd-course-webapp.git'
        targetRevision: '{{head_sha}}'
        path: helm/webapp
      project: "default"
      destination:
        server: https://AB4CABC42894FD7A6E3EF4E8C721DF85.gr7.us-east-1.eks.amazonaws.com
        namespace: webapp-{{branch}}-{{number}}
      syncPolicy:
         syncOptions:
          - CreateNamespace=true
